version: 2.1

orbs:
  node: circleci/node@5.0.0
  coveralls: coveralls/coveralls@1.0.6
jobs:
  executor: node/default
  build:
    docker:
      - image: circleci/node:16.13.1
    steps:
      - checkout
        - node/install-packages

      - coveralls/upload:
          path_to_lcov: ./final-coverage/lcov.info

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
