version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/node:16.13.1
    steps:
      - checkout

      - run:
          name: update-npm
          command: sudo npm install -D

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json"}}

      - save_cache:
          key: dependency-cache-{{ checksum "package.json"}}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
