version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/node:16.13.1

    steps:
      - checkout
      - run:
          name: update-npm
          command: sudo npm install
  test:
    docker:
      - image: circleci/node:16.13.1
    steps:
      - checkout
      - run: npm test

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test
